#!/usr/bin/env python3
"""Calibrate deterministic visual QA using positive replica-library examples."""

from __future__ import annotations

import argparse
import json
import statistics
import subprocess
import sys
import tempfile
from collections import defaultdict
from pathlib import Path
from typing import Any

SUPPORTED_EXT = {".png", ".jpg", ".jpeg", ".svg"}
MAX_PER_FAMILY = 3


def load_index(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"Index JSON not found: {path}. Run index-replica-patterns.py first.")
    return json.loads(path.read_text())


def candidate_outputs(case: dict[str, Any], roots: dict[str, str]) -> list[Path]:
    root = Path(roots["Python" if case["language"].startswith("Python") else "R"])
    case_root = root / case["relative_path"]
    out: list[Path] = []
    for rel in case.get("output_examples", []):
        if rel.startswith("..."):
            continue
        path = case_root / rel
        if path.suffix.lower() in SUPPORTED_EXT and path.exists():
            out.append(path)
    return out


def run_visual_qa(script: Path, image: Path, out_dir: Path) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run([sys.executable, str(script), str(image), "--out", str(out_dir)], text=True, capture_output=True)
    if proc.returncode != 0:
        return {"error": proc.stderr or proc.stdout, "status": "error", "image": str(image)}
    return json.loads((out_dir / "visual_qa.json").read_text())["image_qa"]


def pick_samples(index: dict[str, Any]) -> tuple[list[tuple[dict[str, Any], Path]], list[dict[str, Any]]]:
    by_family: dict[str, list[tuple[dict[str, Any], Path]]] = defaultdict(list)
    pdf_only: list[dict[str, Any]] = []
    roots = index["roots"]
    for case in index["cases"]:
        outputs = candidate_outputs(case, roots)
        if outputs:
            by_family[case["figure_family"]].append((case, outputs[0]))
        elif "pdf" in case.get("output_types", []):
            pdf_only.append(case)
    samples: list[tuple[dict[str, Any], Path]] = []
    for family in sorted(by_family):
        family_cases = by_family[family]
        priority = sorted(
            family_cases,
            key=lambda item: (
                0 if item[0]["dependency_complexity"] in {"low", "medium"} else 1,
                item[0]["case_dir"],
            ),
        )
        samples.extend(priority[:MAX_PER_FAMILY])
    return samples, pdf_only


def num(value: Any) -> float | None:
    try:
        return float(value)
    except Exception:
        return None


def quantiles(values: list[float]) -> dict[str, float | None]:
    if not values:
        return {"min": None, "median": None, "max": None}
    return {
        "min": round(min(values), 4),
        "median": round(statistics.median(values), 4),
        "max": round(max(values), 4),
    }


def metric_row(rows: list[dict[str, Any]], metric: str) -> dict[str, float | None]:
    vals = [v for v in (num(r.get(metric)) for r in rows) if v is not None]
    return quantiles(vals)


def nested_metric_row(rows: list[dict[str, Any]], outer: str, inner: str) -> dict[str, float | None]:
    vals: list[float] = []
    for r in rows:
        outer_value = r.get(outer, {})
        if isinstance(outer_value, dict):
            value = num(outer_value.get(inner))
            if value is not None:
                vals.append(value)
    return quantiles(vals)


def calibration_note(family: str, rows: list[dict[str, Any]]) -> str:
    warn_count = sum(1 for r in rows if r.get("status") == "warn")
    fail_count = sum(1 for r in rows if r.get("status") == "fail")
    if fail_count:
        return "At least one positive example failed deterministic QA; inspect family-specific thresholds before changing global limits."
    if warn_count:
        if "heatmap" in family.lower() or "manhattan" in family.lower() or "phylogenetic" in family.lower():
            return "Warnings may be legitimate density signals for this family; prefer family-specific interpretation."
        return "Warnings likely mark label, color, or layout risks worth preserving as calibration examples."
    return "Current deterministic thresholds accept these positive examples."


def write_report(results: list[dict[str, Any]], pdf_only: list[dict[str, Any]], out_md: Path, out_json: Path) -> None:
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps({"samples": results, "pdf_only_cases": pdf_only}, indent=2, ensure_ascii=False) + "\n")
    by_family: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in results:
        by_family[row["figure_family"]].append(row)
    lines = [
        "# Visual QA Calibration From Replica Library",
        "",
        "Generated by `scripts/calibrate-visual-qa.py`. Samples are treated as positive calibration examples, not as material to copy. The purpose is to learn normal metric ranges and identify where deterministic visual QA needs family-specific interpretation.",
        "",
        "## Scope",
        "",
        f"- Raster/SVG positive samples analyzed: {len(results)}",
        f"- PDF-only cases not directly analyzed by v1 QA: {len(pdf_only)}",
        "- PDF limitation: current `visual-qa-rendered-image.py` analyzes PNG/JPG and structurally inspects SVG; PDF-only examples require a rasterization step before deterministic image QA.",
        "",
        "## Family Ranges",
        "",
        "| family | n | statuses | readiness | content density | blank margin | text burden | line burden | colors | grayscale risk note | calibration note |",
        "|---|---:|---|---|---|---|---|---|---|---|---|",
    ]
    for family in sorted(by_family):
        rows = by_family[family]
        statuses = ", ".join(f"{status}={sum(1 for r in rows if r.get('status') == status)}" for status in sorted({r.get("status", "unknown") for r in rows}))
        readiness = metric_row(rows, "manuscript_readiness_score")
        density = metric_row(rows, "content_density")
        blank = metric_row(rows, "blank_margin_fraction")
        text = metric_row(rows, "text_burden_score")
        line = nested_metric_row(rows, "line_burden", "line_burden_score")
        colors = metric_row(rows, "color_count_estimate")
        gray_warnings = sum(1 for r in rows for risk in r.get("risks", []) if risk.get("code") in {"grayscale_discrimination_risk", "low_grayscale_contrast"})
        lines.append(
            f"| {family} | {len(rows)} | {statuses} | {readiness} | {density} | {blank} | {text} | {line} | {colors} | {gray_warnings} warning(s) | {calibration_note(family, rows)} |"
        )
    lines += [
        "",
        "## Sample-Level Results",
        "",
        "| case | family | image | size | aspect | status | readiness | density | blank | text burden | line burden | color count | top risks |",
        "|---|---|---|---|---:|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for r in results:
        risks = [risk.get("code", "") for risk in r.get("risks", []) if risk.get("status") != "pass"]
        line_burden = r.get("line_burden", {}).get("line_burden_score")
        lines.append(
            "| "
            + " | ".join([
                r["case_dir"].replace("|", "/"),
                r["figure_family"],
                f"`{r['image']}`",
                "x".join(str(x) for x in r.get("image_size_px", [])),
                str(round(float(r.get("aspect_ratio", 0)), 3)) if r.get("aspect_ratio") is not None else "-",
                str(r.get("status")),
                str(r.get("manuscript_readiness_score")),
                str(r.get("content_density")),
                str(r.get("blank_margin_fraction")),
                str(r.get("text_burden_score")),
                str(line_burden),
                str(r.get("color_count_estimate")),
                ", ".join(risks[:4]) if risks else "-",
            ])
            + " |"
        )
    lines += [
        "",
        "## Calibration Conclusions",
        "",
        "- Good figures do not share one universal density range. Heatmaps, tree rings, Manhattan plots, and UpSet-like matrices can be legitimately dense.",
        "- Distribution and grouped-comparison figures should have low-to-moderate text burden; high burden in these families usually indicates annotation or label overload.",
        "- Grayscale discrimination warnings should remain active. Positive examples can still use colors that are risky for grayscale printing.",
        "- Saturation warnings should not be globally disabled; decorative replica cases confirm why family/style context matters.",
        "- PDF-only examples are a coverage gap for v1. Calibration should prefer sibling PNGs or add a controlled PDF rasterization step in a later version.",
        "",
        "## Threshold Guidance",
        "",
        "- Keep global text-burden warnings conservative for group/distribution/scatter figures.",
        "- Add family-specific interpretation in reports for heatmap, Manhattan, tree-ring, and set-matrix figures before lowering global thresholds.",
        "- Treat `warn` as a review trigger, not automatic failure, when the selected pattern document expects dense structure.",
        "- Do not claim manuscript-ready from deterministic metrics alone; use human or vision-model review for aesthetics, label meaning, and scientific hierarchy.",
    ]
    if pdf_only:
        lines += ["", "## PDF-Only Cases Needing Raster QA", ""]
        for c in pdf_only[:40]:
            lines.append(f"- `{c['case_dir']}` ({c['figure_family']})")
        if len(pdf_only) > 40:
            lines.append(f"- ...(+{len(pdf_only) - 40} more)")
    out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run visual QA calibration on positive replica examples.")
    parser.add_argument("--index-json", default="paperplot-skills/reports/nature-replica-pattern-index.json")
    parser.add_argument("--out-md", default="paperplot-skills/reports/visual-qa-calibration-from-replica-library.md")
    parser.add_argument("--out-json", default="paperplot-skills/reports/visual-qa-calibration-from-replica-library.json")
    parser.add_argument("--qa-root", default="/tmp/paperplot-replica-visual-calibration")
    args = parser.parse_args()

    index = load_index(Path(args.index_json))
    samples, pdf_only = pick_samples(index)
    script = Path(__file__).with_name("visual-qa-rendered-image.py")
    results: list[dict[str, Any]] = []
    qa_root = Path(args.qa_root)
    with tempfile.TemporaryDirectory(prefix="paperplot-calibration-") as tmp:
        tmp_path = Path(tmp)
        for i, (case, image) in enumerate(samples, start=1):
            qa = run_visual_qa(script, image, tmp_path / f"sample_{i:03d}")
            row = dict(qa)
            row["case_dir"] = case["case_dir"]
            row["figure_family"] = case["figure_family"]
            row["image"] = str(image)
            results.append(row)
    qa_root.mkdir(parents=True, exist_ok=True)
    write_report(results, pdf_only, Path(args.out_md), Path(args.out_json))
    print(f"calibrated {len(results)} positive examples")
    print(f"wrote {args.out_md}")
    print(f"wrote {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
