#!/usr/bin/env python3
"""Run real visual pressure scenarios for paperplot-skills."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

try:
    from PIL import Image, ImageEnhance, ImageOps
except Exception:
    Image = None

ROOT = Path(__file__).resolve().parents[1]
VISUAL_QA = ROOT / "scripts" / "visual-qa-rendered-image.py"
COMPARE = ROOT / "scripts" / "compare-old-new-figures.py"
REPORT = ROOT / "reports" / "visual-qa-real-figure-test-report.md"

FIXTURES = [
    {
        "scenario": "visual-gs-barplot-burden",
        "path": Path("/Users/qingguozeng/Documents/1-博士课题/1-藜麦泛基因组/10-GS/final_results/figures/fig4_quality_traits.png"),
        "expect_status": {"warn", "fail"},
        "expect_any_risk": {"saturated_presentation_palette", "gridline_or_long_line_burden", "excessive_blank_margin", "thumbnail_readability_risk", "high_text_or_tick_density"},
    },
    {
        "scenario": "visual-gs-label-overlap-risk",
        "path": Path("/Users/qingguozeng/Documents/1-博士课题/1-藜麦泛基因组/10-GS/final_results/figures/figS1_gxe_vs_prediction.png"),
        "expect_status": {"warn", "fail"},
        "expect_any_risk": {"high_text_or_tick_density", "label_overlap_or_large_annotation_risk", "thumbnail_readability_risk", "low_content_density", "excessive_blank_margin", "gridline_or_long_line_burden"},
    },
    {
        "scenario": "visual-gs-quality-trait-accuracy",
        "path": Path("/Users/qingguozeng/Documents/1-博士课题/1-藜麦泛基因组/10-GS/final_results/figures/figS1_quality_trait_accuracy.png"),
        "expect_status": {"warn", "fail"},
        "expect_any_risk": {"high_text_or_tick_density", "gridline_or_long_line_burden", "thumbnail_readability_risk", "saturated_presentation_palette"},
    },
    {
        "scenario": "visual-nlr-svg-presentation-style-count",
        "path": Path("/Users/qingguozeng/Documents/1-博士课题/1-藜麦泛基因组/7-Pangenome/3-Structure/NLR/FINAL_NLR_ANALYSIS_RELEASE/03_pangenome_results/plots/figures/high_nlr_count_by_sample.svg"),
        "expect_status": {"warn", "fail"},
        "expect_any_risk": {"oversized_svg_title_or_text", "huge_centered_title", "svg_gridline_burden"},
    },
    {
        "scenario": "visual-nlr-svg-presentation-style-panclass",
        "path": Path("/Users/qingguozeng/Documents/1-博士课题/1-藜麦泛基因组/7-Pangenome/3-Structure/NLR/FINAL_NLR_ANALYSIS_RELEASE/03_pangenome_results/plots/figures/high_nlr_panclass_summary.svg"),
        "expect_status": {"warn", "fail"},
        "expect_any_risk": {"oversized_svg_title_or_text", "huge_centered_title", "svg_gridline_burden"},
    },
]

FAMILY_FIXTURES = [
    {
        "scenario": "visual-family-lollipop-threshold",
        "path": ROOT / "reports" / "redraw-benchmark" / "high_nlr_count_by_sample_pattern_redraw.png",
        "family": "lollipop",
        "expect_status": {"pass", "warn"},
        "forbid_risk": {"gridline_or_long_line_burden"},
    },
]


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, text=True, capture_output=True)


def risk_codes(result: dict[str, Any]) -> set[str]:
    return {item.get("code", "") for item in result.get("top_risks", [])}


def run_visual(path: Path, out: Path) -> dict[str, Any]:
    proc = run([sys.executable, str(VISUAL_QA), str(path), "--out", str(out)])
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    return json.loads((out / "visual_qa.json").read_text())["image_qa"]


def run_visual_family(path: Path, out: Path, family: str) -> dict[str, Any]:
    proc = run([sys.executable, str(VISUAL_QA), str(path), "--out", str(out), "--family", family])
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    return json.loads((out / "visual_qa.json").read_text())["image_qa"]


def make_degraded(src: Path, dst: Path) -> bool:
    if Image is None or not src.exists() or src.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
        return False
    img = Image.open(src).convert("RGB")
    low = ImageEnhance.Contrast(img).enhance(0.45)
    low = ImageEnhance.Color(low).enhance(0.35)
    canvas = Image.new("RGB", (int(low.width * 1.35), int(low.height * 1.35)), "white")
    canvas.paste(low, (int(low.width * 0.18), int(low.height * 0.18)))
    canvas.save(dst)
    return True


def write_report(rows: list[dict[str, Any]], compare_row: dict[str, Any] | None) -> None:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Visual QA real figure test report",
        "",
        "This report is generated by `scripts/run-visual-pressure-scenarios.py`. It uses user-provided real GS PNG figures and NLR SVG figures as regression fixtures. The test diagnoses figures only; it does not redraw them.",
        "",
        "## Scenario results",
        "",
        "| scenario | input | status | score | pass | top risks |",
        "|---|---|---:|---:|---|---|",
    ]
    for row in rows:
        risks = ", ".join(row.get("risk_codes", [])) or row.get("detail", "")
        lines.append(f"| {row['scenario']} | `{row['input']}` | {row.get('status','')} | {row.get('score','')} | {row['pass']} | {risks} |")
    if compare_row:
        lines += [
            "",
            "## Old-vs-new synthetic comparison",
            "",
            f"- verdict: `{compare_row.get('verdict')}`",
            f"- status: `{compare_row.get('status')}`",
            f"- pass: `{compare_row.get('pass')}`",
        ]
    lines += [
        "",
        "## What automatic visual QA caught",
        "",
        "- Presentation-style title and font burden in SVG plots.",
        "- Gridline/long-line burden in SVG and raster plots.",
        "- Saturated color or grayscale discrimination risks in raster plots.",
        "- Blank margin/content density and thumbnail readability risks.",
        "",
        "## Remaining limits",
        "",
        "- No OCR/Tesseract in v1, so exact text overlap is approximated by component density and SVG text structure.",
        "- SVG is structurally inspected but not rasterized.",
        "- Scientific correctness still requires data, metadata, and user confirmation.",
    ]
    REPORT.write_text("\n".join(lines) + "\n")


def main() -> int:
    root = Path(tempfile.mkdtemp(prefix="paperplot-visual-pressure-"))
    rows = []
    for fixture in FIXTURES:
        scenario = fixture["scenario"]
        path = fixture["path"]
        out = root / scenario
        if not path.exists():
            rows.append({"scenario": scenario, "input": str(path), "pass": True, "status": "fixture_missing", "score": "", "risk_codes": [], "detail": "fixture_missing"})
            continue
        try:
            result = run_visual(path, out)
            codes = risk_codes(result)
            ok = result.get("status") in fixture["expect_status"] and bool(codes.intersection(fixture["expect_any_risk"]))
            rows.append({"scenario": scenario, "input": str(path), "pass": ok, "status": result.get("status"), "score": result.get("manuscript_readiness_score"), "risk_codes": sorted(codes), "output_dir": str(out)})
        except Exception as exc:
            rows.append({"scenario": scenario, "input": str(path), "pass": False, "status": "error", "score": "", "risk_codes": [], "detail": str(exc)})
    for fixture in FAMILY_FIXTURES:
        scenario = fixture["scenario"]
        path = fixture["path"]
        out = root / scenario
        if not path.exists():
            rows.append({"scenario": scenario, "input": str(path), "pass": True, "status": "fixture_missing", "score": "", "risk_codes": [], "detail": "fixture_missing"})
            continue
        try:
            result = run_visual_family(path, out, fixture["family"])
            codes = risk_codes(result)
            ok = result.get("status") in fixture["expect_status"] and not bool(codes.intersection(fixture["forbid_risk"]))
            rows.append({"scenario": scenario, "input": str(path), "pass": ok, "status": result.get("status"), "score": result.get("manuscript_readiness_score"), "risk_codes": sorted(codes), "output_dir": str(out)})
        except Exception as exc:
            rows.append({"scenario": scenario, "input": str(path), "pass": False, "status": "error", "score": "", "risk_codes": [], "detail": str(exc)})
    compare_row = None
    base = FIXTURES[0]["path"]
    if base.exists() and Image is not None:
        degraded = root / "degraded_fig4.png"
        if make_degraded(base, degraded):
            out = root / "visual-old-vs-new-metric-delta"
            proc = run([sys.executable, str(COMPARE), str(base), str(degraded), "--out", str(out)])
            if proc.returncode == 0:
                payload = json.loads((out / "old_vs_new_visual_qa.json").read_text())["old_vs_new_visual_qa"]
                compare_row = {"pass": payload.get("verdict") in {"worse", "mixed"} and payload.get("status") in {"warn", "fail"}, "verdict": payload.get("verdict"), "status": payload.get("status"), "output_dir": str(out)}
            else:
                compare_row = {"pass": False, "verdict": "error", "status": "error", "detail": proc.stderr or proc.stdout}
    write_report(rows, compare_row)
    print("scenario pass status")
    for row in rows:
        print(f"{row['scenario']}\t{row['pass']}\t{row.get('status')}\t{row.get('score')}\t{','.join(row.get('risk_codes', []))}")
    if compare_row:
        print(f"visual-old-vs-new-metric-delta\t{compare_row['pass']}\t{compare_row.get('status')}\t{compare_row.get('verdict')}")
    print(f"temporary visual pressure root: {root}")
    print(f"visual QA real figure test report: {REPORT}")
    all_ok = all(row["pass"] for row in rows) and (compare_row is None or compare_row.get("pass"))
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
