#!/usr/bin/env Rscript
source("paperplot-skills/scripts/paperplot_helpers.R")
check <- function(x, label) if (!isTRUE(x)) stop(label)
fails <- function(expr, label) check(inherits(tryCatch(force(expr), error = identity), "error"), label)
root <- Sys.getenv("PAPERPLOT_PROJECT_TEST_OUTPUT", tempfile("pp-project-test-"))
dir.create(root, recursive = TRUE, showWarnings = FALSE)
builder <- file.path(root, "builder.R")
writeLines(c("build_panel <- function(inputs, context) {", "d <- read.csv(inputs$values)",
  "p <- ggplot2::ggplot(d, ggplot2::aes(x,y)) + ggplot2::geom_point(colour=context$shared$colors$signal) + ggplot2::labs(title=context$question)",
  "list(plot=p, evidence=d)", "}"), builder)
ids <- c("association", "comparison", "profile", "summary")
panels <- lapply(seq_along(ids), function(i) {
  csv <- file.path(root, paste0(ids[i], ".csv")); write.csv(data.frame(x=1:5, y=(1:5) + i/10), csv, row.names = FALSE)
  list(id=ids[i], title=LETTERS[i], question=paste("Synthetic view", LETTERS[i]), role=if(i==1) "primary" else "supporting",
       script=builder, inputs=list(values=csv), dependencies_declared=TRUE, shared_keys=list("colors"))
})
project <- file.path(root, "figure2")
state <- pp_project_create("figure2", "Demonstrate incremental figure construction with simulated data.", panels,
  project=project, shared=list(colors=list(signal="#173B73"), unused="initial"), mode="demo")
check(file.exists(file.path(project,"layouts/r000001/sketch.png")), "Layout sketch")
check(is.null(state$layout_confirmed), "Layout starts pending")
fails(pp_project_build_panel(project,"A"), "Must confirm layout")
fails(ppp_layout(list(width_mm=183),ids), "Width requires exception")
check(ppp_layout(list(width_mm=183,width_exception="explicit IGS width"),ids)$width_mm==183,"Explicit exception")
check(ppp_layout(list(width_mm=160),ids)$width_mm==160,"Smaller canvas allowed")
check(pp_project_create("ignored","ignored",panels,project=project)$figure_id=="figure2","Resume existing project")
pp_project_confirm_layout(project,"test user")
lock <- file.path(project,".project-lock"); dir.create(lock)
fails(pp_project_confirm_layout(project,"test user"),"Concurrent write denied")
unlink(lock,recursive=TRUE)
for (id in ids) {
  built <- pp_project_build_panel(project,id)
  check(built$success,paste("Build",id,built$error))
}
before <- pp_project_status(project)
original <- vapply(before$panels, function(p) p$current, character(1))
for (id in ids) {
  ctx <- jsonlite::fromJSON(file.path(project,before$panels[[id]]$revisions[[original[[id]]]]$dir,"context.json"))
  check(ctx$render_spec$width_mm==90,"Panel uses planned slot, not fixed 89 mm")
}
check(pp_project_build_panel(project,"A")$reused,"Same build reused")
pp_project_review(project,"A","pass","test user")
newbuilder <- file.path(root,"builder-b.R")
writeLines(sub('title=context$question','title=paste(context$question, "revised")',readLines(builder),fixed=TRUE),newbuilder)
revision <- pp_project_revise_panel(project,"B",script=newbuilder,reason="Change B title only")
check(revision$success,paste("Revise/assemble",revision$result$error))
after <- pp_project_status(project)
check(identical(vapply(after$panels[ids[c(1,3,4)]],function(p)p$current,character(1)),original[ids[c(1,3,4)]]),"Only B rebuilt")
check(after$panels$association$review$decision=="pass","A review preserved")
check(after$panels$comparison$current!=original[[2]],"New B revision")
for (id in ids[c(1,3,4)]) {
  check(identical(after$panels[[id]]$revisions[[original[[id]]]]$object_md5,
                  before$panels[[id]]$revisions[[original[[id]]]]$object_md5), "Unchanged panel object hashes")
}
check(revision$result$geometry$status=="measured",paste("Actual geometry",revision$result$geometry$reason))
check(length(revision$result$geometry$context_previews)==4,"Context previews from final geometry")
pp_project_review(project,"A","fail","test user")
fails(pp_project_assemble(project,final=TRUE),"Failed panel review blocks final assembly")
fails(pp_project_review(project,"figure","pass","test user"),"Failed panel review blocks figure approval")
pp_project_review(project,"A","pass","test user")
first_b <- after$panels$comparison$current
bad <- file.path(root,"bad.R"); writeLines('build_panel <- function(inputs, context) stop("intentional failure")',bad)
attempt <- pp_project_revise_panel(project,"B",script=bad,reason="Failure recovery test")
check(!attempt$success,"Failure recorded")
check(pp_project_status(project)$panels$comparison$current==first_b,"Failed build leaves current pointer")
fails(pp_project_assemble(project,final=TRUE),"Stale panel blocks final assembly")
pp_project_restore(project,"B",first_b)
check(pp_project_status(project)$panel_status$comparison$fresh,"Historical restore")

pp_project_configure(project,list(shared=list(colors=list(signal="#173B73"),unused="changed")))
check(all(vapply(pp_project_status(project)$panel_status,function(s)s$fresh,logical(1))),"Unused shared fields do not invalidate")
pp_project_configure(project,list(shared=list(colors=list(signal="#D55E00"))))
check(all(!vapply(pp_project_status(project)$panel_status,function(s)s$fresh,logical(1))),"Shared colors invalidate users")
draft <- pp_project_assemble(project)
check(draft$success,paste("Shared rebuild",draft$result$error))
layout <- pp_project_status(project)$layout
layout$design <- "AB\nCC\nDD"; layout$heights <- list(1,1,1)
pp_project_set_layout(project,layout)
fails(pp_project_assemble(project),"Changed layout requires confirmation")
pp_project_confirm_layout(project,"test user")
check(pp_project_assemble(project)$success,"New placements rebuilt")
pp_project_restore(project,"layout","r000001")
check(is.null(pp_project_status(project)$layout_confirmed),"Restoring layout requires review")
pp_project_confirm_layout(project,"test user")
check(pp_project_assemble(project)$success,"Restored layout assembled")

# A data edit cannot pass as a styling revision or be silently rebuilt in a draft.
csv <- panels[[3]]$inputs$values; write.csv(data.frame(x=1:5,y=11:15),csv,row.names=FALSE)
badstyle <- pp_project_build_panel(project,"C")
check(!badstyle$success,"Scientific change rejected as style")
scientific <- pp_project_build_panel(project,"C",change_type="scientific",reason="Explicit fixture data update")
check(scientific$success,"Explicit scientific revision")
check(pp_project_status(project)$assembly_status$status=="stale", "Assembly status follows panel revision changes")
pp_project_configure(project,list(guide_semantics="different"),panel="B")
layout <- pp_project_status(project)$layout; layout$guides <- "collect"
pp_project_set_layout(project,layout); pp_project_confirm_layout(project,"test user")
fails(pp_project_assemble(project),"Conflicting guide meanings rejected")

partial <- lapply(panels[1:2], function(p) {p$script <- NULL; p})
partial_project <- file.path(root,"partial")
invisible(pp_project_create("partial","Simulated incomplete layout.",partial,project=partial_project,mode="demo"))
pp_project_confirm_layout(partial_project,"test user")
fails(pp_project_assemble(partial_project,final=TRUE),"Incomplete panels cannot be final")
draft <- pp_project_assemble(partial_project)
check(draft$success && length(draft$result$incomplete)==2, "Explicit placeholder draft")
qa <- jsonlite::fromJSON(file.path(partial_project,draft$result$dir,"figure_production_qa.json"))
check(qa$final$checks$project_panels_complete=="fail","One QA contract includes project incompleteness")
external <- file.path(root,"external.R"); writeLines('build_panel <- function(inputs,context) read.csv("undeclared.csv")',external)
check(length(ppp_dependency_warnings(external))>0,"Unregistered input reads flagged")
categorical <- ggplot2::ggplot(data.frame(x=1:2,y=c("a","b")),ggplot2::aes(x,y))+ggplot2::geom_point()
fails(ppp_validate_shared_order(categorical,"a"),"Shared order cannot remove a category")
regions <- list(data_regions=list(a=list(top_mm=10,height_mm=40),b=list(top_mm=11,height_mm=40)))
check(ppp_row_alignment(regions,list(list(panels=list("a","b"),order=list("a","b"))))$status=="fail","Physical row offset detected")
cat("Figure project tests passed. Artifacts:",project,"\n")
