#!/usr/bin/env Rscript
# Small real-font fixture: no external visual QA, no manuscript acceptance.
source('paperplot-skills/scripts/paperplot_helpers.R')
check <- function(x, message) if(!isTRUE(x)) stop(message, call.=FALSE)
fails <- function(expr) check(inherits(tryCatch(force(expr),error=identity),'error'),'Expected refusal')
args <- commandArgs(TRUE)
out <- if(length(args)) args[[1]] else file.path('tmp',paste0('pdf-jpg-contract-',Sys.getpid()))
if(dir.exists(out)) stop('Use a new fixture directory.')
dir.create(out,recursive=TRUE)
d <- data.frame(x=1:3,y=c(1,3,2))
p <- ggplot2::ggplot(d,ggplot2::aes(x,y))+ggplot2::geom_point()+ggplot2::labs(x='Mass',y='Response')+pp_theme()
spec <- pp_render_spec(2,mode='production',expected_labels=c('Mass','Response'))
combo <- pp_normalize_production(patchwork::wrap_plots(p,p),spec)
files <- pp_save_all(combo,file.path(out,'tagged'),width=spec$width_mm/10,height=spec$height_mm/10,dpi=spec$dpi,finalize_plot=FALSE,quality=95)
audit <- pp_run_export_audit(files,spec,file.path(out,'good'))
keys <- c('.pdf_present','.jpg_present','pdf_page_mm','pdf_typography','pdf_font_embedding','pdf_panel_tags','pdf_required_labels','jpg_encoding','jpg_dpi','jpg_rgb','jpg_pixels')
for(key in keys) check(identical(audit$checks[[key]],'pass'),paste('Real default fixture:',key))
check(!any(file.exists(file.path(out,paste0('tagged.',c('png','svg'))))),'No hidden legacy export')
wrong <- spec; wrong$expected_tags <- list('A','B')
check(identical(pp_run_export_audit(files,wrong,file.path(out,'wrong-case'))$checks$pdf_panel_tags,'fail'),'Wrong PDF tag case fails')
wrong <- spec; wrong$expected_labels <- list('Missing required label')
check(identical(pp_run_export_audit(files,wrong,file.path(out,'missing-label'))$checks$pdf_required_labels,'fail'),'Missing PDF label fails')
check(identical(pp_run_export_audit(files['jpg'],spec,file.path(out,'missing-pdf'))$checks[['.pdf_present']],'fail'),'Missing requested PDF fails')
for(formats in list(character(),'',NA_character_,c('jpg','JPG'),'../pdf','pdf/evil')) {
  fails(pp_save_all(combo,file.path(out,'invalid'),formats=formats))
  check(!length(Sys.glob(file.path(out,'invalid*'))),'Invalid formats create nothing')
}
hashes <- tools::md5sum(files)
fails(pp_save_all(combo,file.path(out,'tagged')))
check(identical(hashes,tools::md5sum(files)),'No overwrite changes existing files')
# This check is byte-level, not a visual assertion: JFIF updates leave compressed data unchanged.
raw_path <- file.path(out,'density-only.jpg')
ragg::agg_jpeg(raw_path,width=100,height=100,res=300,quality=95)
grid::grid.newpage();grid::grid.rect(gp=grid::gpar(fill='white'));grDevices::dev.off()
before <- readBin(raw_path,'raw',n=file.info(raw_path)$size)
pp_set_jpeg_dpi(raw_path,300)
after <- readBin(raw_path,'raw',n=file.info(raw_path)$size)
if(length(after)==length(before)+18L) check(identical(c(after[1:2],after[-seq_len(20)]),before),'Density insertion preserves entire original compressed JPEG')
check(identical(as.integer(after[14:18]),c(1L,1L,44L,1L,44L)),'JFIF inches and 300x300 density')
pp_set_jpeg_dpi(raw_path,300)
check(identical(after,readBin(raw_path,'raw',n=file.info(raw_path)$size)),'JFIF density update is idempotent')
cat('PDF/JPG real-font, label/tag, safety and lossless metadata tests passed:',out,'\n')
